name: Build python script into binary file

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version (e.g., v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clean old build files
      shell: bash
      run: rm -rf build dist *.spec

    - name: Build with PyInstaller
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          pyinstaller --onedir --name ProjectMatching main.py
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          pyinstaller --onefile --name ProjectMatching main.py
        fi
      shell: bash

    - name: Prepare distribution files
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          cp README.txt dist/ProjectMatching/README.txt
          cd dist
          powershell Compress-Archive -Path ProjectMatching -DestinationPath ProjectMatching-windows.zip
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          mv dist/ProjectMatching dist/ProjectMatching-macos
          cp README.txt dist/README.txt
        fi
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProjectMatching-${{ matrix.os }}
        path: |
          dist/ProjectMatching-windows.zip
          dist/ProjectMatching-macos
          dist/README.txt

  release:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: |
            ProjectMatching-macos
            ProjectMatching-windows.zip
            README.txt
